CREATE TABLE scanner_state (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	network VARCHAR(50) NOT NULL,
	monitor_address VARCHAR(42) NOT NULL,
	accumulated_fees VARCHAR(255) DEFAULT "0",
	last_block INT UNSIGNED NOT NULL DEFAULT 0,
	time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE tx (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	tx_eth_hash VARCHAR(66) NOT NULL,
	tx_glitch_hash VARCHAR(66),
	from_eth_address VARCHAR(42) NOT NULL,
	to_glitch_address VARCHAR(48),
	amount VARCHAR(255) NOT NULL,
	business_fee_amount VARCHAR(255),
	business_fee_percentage VARCHAR(255),
	`state` enum('TO_PROCESS', 'PROCESSING', 'PROCESSED') DEFAULT 'TO_PROCESS',
	error TEXT,
	time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE fee_transaction (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`hash` VARCHAR(66),
	amount VARCHAR(255) NOT NULL,
	time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);